apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstapp
  namespace: labgke
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/sonorous-charge-339422/myfirstapp/myfirstapp:2.0
        env:
        - name: REDIS_HOST
          value: 127.0.0.1
        - name: MESSAGE
          value: "Meu primeiro app"
        ports:
        - name: http
          containerPort: 80
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
